apiVersion: v1
kind: Service
metadata:
  name: nacos - cluster - service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: nacos - cluster
  ports:
  - protocol: TCP
    port: 8848
    targetPort: 8848
